# Generated by Django 4.2.7 on 2024-07-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=40)),
                ('District', models.CharField(max_length=30)),
                ('DistrictCode', models.CharField(max_length=90)),
            ],
        ),
        migrations.DeleteModel(
            name='Dummy',
        ),
    ]
