# Generated by Django 4.2.7 on 2024-07-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_district_delete_dummy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='State',
            field=models.CharField(default='Sikkim', max_length=40),
        ),
    ]
