# Generated by Django 4.2.7 on 2024-07-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_alter_district_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='District',
            field=models.CharField(default='Sikkim', max_length=30),
        ),
        migrations.AlterField(
            model_name='district',
            name='DistrictCode',
            field=models.CharField(default='11110002', max_length=90),
        ),
    ]
