# Generated by Django 4.2.7 on 2024-07-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_alter_district_district_alter_district_districtcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='District',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='district',
            name='DistrictCode',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='district',
            name='State',
            field=models.CharField(default='Sikkim'),
        ),
    ]
