# Generated by Django 4.2.7 on 2024-07-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_alter_district_district_alter_district_districtcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelsAndRestraunts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HotelName', models.CharField(max_length=190)),
                ('HotelOwner', models.CharField(max_length=70)),
                ('phonenumber', models.CharField(max_length=10)),
                ('Remarks', models.CharField(max_length=900)),
            ],
        ),
    ]
