# Generated by Django 4.2.7 on 2024-07-31 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
